### ISSUE TITLE
Папку public не коммитят

### ISSUE THREAD

**Issue by Nitive** [Maksimus-Prime/task-two-ui-kit#2]
public не коммитят, потому что её контент вычисляется динамически и
1. Нет смысла хранить то, что можно собрать одной командой на основе имеющегося кода
1. Там может быть много файлов, которые будут отжирать место на диске, долго скачиваться и так далее
1. При мёрже веток постоянно будут конфликты

Вместо этого в `package.json` добавляют команду `build`, при помощи которой (`npm run build`) эта папка собирается из исходников

**Comment by kinda-neat** [comment]
Принято. Сейчас она нужна, поэтому оставляю
