### ISSUE TITLE
Инпут вываливается

### ISSUE THREAD

**Issue by shevdi** [Maksimus-Prime/task-two-ui-kit#24]
В макете со всеми элементами конкретно `layout-search-drop-user-profile-container-left__search` выпадает за края.

**Comment by kinda-neat** [comment]
А можно скрин какой-нибудь?)
Как это выглядит у меня
![image](https://user-images.githubusercontent.com/27883524/31501273-f870a704-af93-11e7-93dc-e767f357b28e.png)
![image](https://user-images.githubusercontent.com/27883524/31501333-2d3637ba-af94-11e7-8acd-5fe583908512.png)
или ты про вот этот момент на iPad?
![image](https://user-images.githubusercontent.com/27883524/31501396-588d3a30-af94-11e7-9611-eccac75cec10.png)

**Comment by shevdi** [comment]
Да. Здесь. Извиняюсь, что долго не отвечал. Не заметил, что пришло сообщение.
