### ISSUE TITLE
А можно без float?

### ISSUE THREAD

**Issue by shevdi** [Maksimus-Prime/task-two-ui-kit#25]
В некоторых местах используется float можно убрать. Это касается и первого макета. Тогда без него можно убрать и clearfix. Особенно если это нужно выставить два блока рядом. В этом случае можно просто менять display с inline-block на block и обратно.

**Comment by kinda-neat** [comment]
Убрал float на странице где расположены все элементы ui-kit'a, перевел на "display с inline-block на block и обратно". Можно оставить страницу в первом макете как есть? я там заморочился с папкой shared, так что пусть останется как наглядный пример, ок?
