### ISSUE TITLE
Outline 

### ISSUE THREAD

**Issue by Burize** [Maksimus-Prime/task-two-ui-kit#28]
Не убраны дефолтные outline у инпутов. Этот пункт есть в стандартах.

**Comment by kinda-neat** [comment]
Ты про вот этот пункт?
![image](https://user-images.githubusercontent.com/27883524/31531827-b89830e0-b013-11e7-83a5-b47c5a271501.png)

**Comment by Burize** [comment]
Действительно оказывается нет пункта на это (нужно будет добавить). Вообщем при стилизации дефолтных элементов лучше убирать их outline и заменять своими стилями. Они не везде одинаково работают и не всегда отображаются как надо. У твоих инпутов в safari outline отображается правильно, но в хроме есть просвет между углами инпута и outline. 
![2017-10-13 17 32 50](https://user-images.githubusercontent.com/22253666/31542542-a63ce64c-b03c-11e7-8539-0ec27f5494a0.png)

Ну а вообще бывают и хуже случаи 
![31328350-cd6d0b16-acfe-11e7-90e5-a3de83b2b643](https://user-images.githubusercontent.com/22253666/31542723-6b32a96e-b03d-11e7-9beb-e62a1c998673.png)

**Comment by kinda-neat** [comment]
Правило с outline применяется для элементов формы и элементов ссылок (кнопка-ссылка и т.п.), да? может быть даже ко всему до чего мы можем дотянуться tab'ом, так?

**Comment by kinda-neat** [comment]
Задал свой outline в блоке search, и в форме input'ам и textarea. Могу закрывать ишьюс?
