### ISSUE TITLE
require img

### ISSUE THREAD

**Issue by Burize** [Maksimus-Prime/task-two-ui-kit#31]
Можешь пояснить зачем нужно 
![2017-10-05 11-33-21](https://user-images.githubusercontent.com/22253666/31211410-f53bbe88-a9c2-11e7-9efa-3d86a87d75f2.png)

**Comment by kinda-neat** [comment]
Без этого file-loader не подхватывал картинки, попробую исправить и посмотреть в чем проблема, в прошлом проекте все подхватывалось хотя и использовал тот же loader
