### ISSUE TITLE
элементы и модификаторы в БЭМ

### ISSUE THREAD

**Issue by shevdi** [Maksimus-Prime/task-two-ui-kit#46]
И вообще посмотри семантику элементов. Бывает создается новый класс, т.е. через дефис, где должен быть элемент или модификатор.

**Comment by kinda-neat** [comment]
Ты про вот такие финты ушами?
![image](https://user-images.githubusercontent.com/27883524/32321401-97c30f9e-bff3-11e7-9758-bc6ebd9f0e8c.png)
Если да, то Серега разрешил так схитрить
![image](https://user-images.githubusercontent.com/27883524/32321605-3f9bbf7c-bff4-11e7-8f14-206dfc47068a.png)
![image](https://user-images.githubusercontent.com/27883524/32321667-6c7bef4e-bff4-11e7-828d-9c74aa809f56.png)
![image](https://user-images.githubusercontent.com/27883524/32321637-537f0db4-bff4-11e7-86b7-22121ecd6cfd.png)
