### ISSUE TITLE
Страницы вынести по отдельным папкам

### ISSUE THREAD

**Issue by Burize** [Maksimus-Prime/task-two-ui-kit#53]

**Comment by kinda-neat** [comment]
Т.е. ты хочешь чтобы я html файл каждой страницы вынес в отдельную папку?
С Серегой разговаривали по этому моменту и он сам сказал что в данном случае можно забить на это, пусть они лежат в одном месте и съедают один общий main.css и main.js, просто если я буду переносить, то очень много путей нужно будет поменять, может не стоит ради одного html этого делать?
