### ISSUE TITLE
На каждой странице должен быть всего один блок

### ISSUE THREAD

**Issue by Znack** [Maksimus-Prime/task-two-ui-kit#58]
Сейчас на каждой странице идет как минимум блок самой страницы и внутри блок с постфиксом content. А почему вложенный блок, а не элемент __content? И почему у index.pug целая куча влоденных блоков и это не в рамках всех страниц сделано (не в той же папке)? :)

**Comment by kinda-neat** [comment]
(Сейчас говорю про index.pug) Да, есть такой момент, был issue на эту тему, плиз посмотри что я там  написал в свое оправдание
https://github.com/Maksimus-Prime/task-two-ui-kit/issues/46

**Comment by Znack** [comment]
Я думал, ты там только колонки сделаешь :) Но вообще смысла в тех блоках нет, давай все таки элементами там нафигачь :)
