### ISSUE TITLE
Уйти от цифр в названиях

### ISSUE THREAD

**Issue by Znack** [Maksimus-Prime/task-two-ui-kit#59]
Например, шаги signup назвать по смыслу, что там в шагах делается. От цифр в именах файлов, классов и тд надо уходить по максимуму

**Comment by kinda-neat** [comment]
Как тогда лучше назвать?
Мой вариант:
1-я страница - entering-contact-info.html
2-я - entering-job-and-soc-info.html
3-я - checking-signup-info.html

**Comment by Znack** [comment]
Только без сокращений :)
